### ISSUE TITLE
Unable to reach https://hew.pierrezemb.fr/api/v0/exec

### ISSUE THREAD

**Issue by DamGameHero** [helloexoworld/hew-hands-on#44]
Hello, 

I was following your great tutorial [here](https://helloexoworld.github.io/hew-hands-on/) but the Warp 10 endpoint `https://hew.pierrezemb.fr/api/v0/exec` seems no longer available.  

Can we get the data used in your tutorial to upload them in our own warp 10 instance ?

Thanks

**Comment by PierreZ** [comment]
Hi!

Should be up now :smile: 

```shell

❯ curl -X POST -d "NOW" https://hew.pierrezemb.fr/api/v0/exec 
[1640071297558854]
```

I restarted the Docker and everything is back to normal.

> Can we get the data used in your tutorial to upload them in our own warp 10 instance ?

Yes! The raw data are not available, but you can retrieve the Docker with the LevelDB files.

```shell
docker run -p 8080:8080 -p 8081:8081 --rm -i helloexoworld/hands-on:latest
```

From that point, you should be able to `FETCH` in streaming using [FETCH API](https://warp10.io/content/03_Documentation/03_Interacting_with_Warp_10/04_Fetching_data/01_Fetching_data) and `format=text` to reimport it in your Warp10.

Do you have another question?

**Comment by DamGameHero** [comment]
No, I don't. Thank you very much !
